### ISSUE TITLE
Any chance for 'sort notes by tags'?

### ISSUE THREAD

**Issue by 097115** [insanum/sncli#34] opened 2017-01-25 10:10 UTC
Like, an additional `yes/no` option, and then `by date` or `by alpha` inside a tag?

**Comment by swalladge** [comment] 2017-01-25 11:32
This sounds like an interesting idea - I'll definitely look into it. I'm not sure how this would work though. Since notes have multiple tags, should the list of tags be sorted, and then the notes sorted by that? How are you thinking it should work exactly? :)

**Comment by 097115** [comment] 2017-01-25 11:41
> Since notes have multiple tags, should the list of tags be sorted, and then the notes sorted by that? How are you thinking it should work exactly? :)

My thinking was that since note's tags can be arranged by a user manually (by entering those in a [specific order](http://i.imgur.com/pozCVxb.png)), then the first tag should be given an advantage… What do you think?

**Comment by swalladge** [comment] 2017-02-10 10:32
@097115 I've added an implementation of sorting notes by tags in the `sort_tags` branch. Please try it out - feedback appreciated! I would also like suggestions for the default keybinding for sort by tags. (Remember that sort by title is `a` and by date is `d`.)

**Comment by 097115** [comment] 2017-02-10 11:39
Now, that looks nice, thanks!

The only problem is that it seems to reset (sorting by tags switches off) after editing a tag or a note - i.e., after the sync process finishes. Don't  know if it's a feature or a bug :).

As per the keybinding, `C-t` seems handy and logical for me: you **sort** with single-letter hotkeys and toggle grouping on and off with a composite one :).

**Comment by swalladge** [comment] 2017-02-10 23:36
> The only problem is that it seems to reset (sorting by tags switches off) after editing a tag or a note - i.e., after the sync process finishes. Don't know if it's a feature or a bug :).

Yes the sorting gets reset on sync - probably more of a bug than a feature.

> As per the keybinding, C-t seems handy and logical for me: you sort with single-letter hotkeys and then toggle grouping on and off with a composite one :).

Wait maybe I misinterpreted what you were requesting. Currently the tags sort is implemented exactly the same as the other sorts - it just sorts the notes with the key being the tags list. Python sorts are stable though, so if you press `d` to sort by date, then the sort-by-tags, notes with the same tags will be sorted by date as well. That isn't by design though - just a by product of sorting twice.

**Comment by 097115** [comment] 2017-02-11 05:36
> Wait maybe I misinterpreted what you were requesting.

No, you didn't :). Everything's OK, really (except for that reset on sync may be), I was just suggesting some sort of explanation for the hotkey choice :).

**Comment by swalladge** [comment] 2017-02-11 06:14
@097115, just pushed a fix for the resetting sort order on sync to that branch. If you could test it out, that would be great! I'll merge to master as soon as I'm happy that it's stable.

**Comment by 097115** [comment] 2017-02-11 06:37
It seems now that "alpha" sorting gets reseted after sync to "date" (and `cfg_sort_mode = alpha` from `.snclirc` doesn't affect startup). As for tag sorting it looks like OK.

**Comment by swalladge** [comment] 2017-02-11 07:14
@097115 pushed some fixes: tag sorting is now deterministic (ties broken by modified date), and it should use the configuration sort mode on startup now (including in `list` and `dump` modes).

**Comment by 097115** [comment] 2017-02-11 07:19
Looks like you can't now sort by alpha and tag? After pressing a key for sort by tags, it switches to sorting by date and tags.

**Comment by swalladge** [comment] 2017-02-11 07:58
Yep that's right. I can't think of any other neat way to have a deterministic sort (so it doesn't 'reset' on sync). Unless we have two 'tags' sorting functions - one with secondary sort being date and the other being by title.

**Comment by 097115** [comment] 2017-02-11 08:05
Well, that's kinda sad news…

**Comment by swalladge** [comment] 2017-02-21 10:36
@097115 how happy are you about the tag sorting? I think I like it like that feature as it is - simple and useful for finding untagged notes. When it's all resolved, I'll merge to master and close the issue. :)

**Comment by swalladge** [comment] 2017-02-21 10:40
Also, any opinions on whether notes without tags should be shown above or below those with tags? Currently notes without tags are below, but my logic is saying without tags should be first.

**Comment by 097115** [comment] 2017-02-21 10:43
Well, not really: in the end, I use now the first iteration, which resets after sync - since I'm more used to alpha sorting, not date.

As for notes without tags, I agree with you, showing them first makes more sense.

**Comment by swalladge** [comment] 2017-02-21 10:52
Improved the ordering - tag sorting is now live as of commit https://github.com/insanum/sncli/commit/605818411ac79bf85c945dd579e14669c2fb8b24

**Closed by swalladge** 2017-02-21 10:52 UTC

**Comment by 1094** [comment] 2019-04-28 18:49
My question is related to this and not actually an "issue" so I didn't want to open a new one: Is there a help file or something that lists all the different configurable items (like sorting) and their options (alpha, date, etc)?

**Comment by swalladge** [comment] 2019-04-29 00:00
@1094 unfortunately not sorry. The best place to start looking at this time is https://github.com/insanum/sncli/blob/master/simplenote_cli/config.py 

Something that would be nice to have in the future is some actual documentation. A fork of this project made for nextcloud notes, nncli, has nice documentation which could be copied/adapted for sncli. See https://nncli.org/ and https://git.danielmoch.com/nncli/

**Comment by 1094** [comment] 2019-04-30 10:23
Most of the `config.py` shows up in the help menu. Which is helpful to a point. After reading this thread, I took a look at the `utils.py` but with my limited (aka almost nil) knowledge of `python` that wasn't very useful.

I'll take a look `nncli` and see what I can gleam from that. Thanks.

**Comment by swalladge** [comment] 2019-04-30 10:31
@1094 which ones in particular are you looking for. I can perhaps help decipher the source code.

If it's the sorting mode, the relevant code is in https://github.com/insanum/sncli/blob/master/simplenote_cli/notes_db.py#L76 . Basically the options are "alpha", "date", and "tags"

**Comment by 1094** [comment] 2019-04-30 10:50
Actually, I started my search because I wanted to sort notes in alphabetical order. Finding this thread just made me realize a) I have no idea what "alpha" means and that b) there are a number of setting and options for a program I use (multiple times *every*day) and I have no idea what they are. These ideas got my curiosity going.

**Comment by 1094** [comment] 2019-04-30 13:02
I can't edit my note (at work at using EI) but I just realized I mistyped that. I do know what "alpha" means. I just didn't realize `sncli` had the sort option.
