### ISSUE TITLE
crash on edit

### ISSUE THREAD

**Issue by stevepowell99** [insanum/sncli#17] opened 2015-04-23 09:04 UTC
hi, sncli crashes when I press e for edit. On ubuntu 14.04, 64bit.

**Comment by axs221** [comment] 2015-04-23 13:37
Hi Steve, I am also on Ubuntu 14.04 64-bit, and this isn't occurring for me. Can you provide some more details? 

* Does it produce a runtime error message / call stack? 
* Can you send your log file (it should be under ~/.sncli/sncli.log I believe)?
* Which screen are you on? 
* What is your EDITOR environment variable set to, if it is set (in your BASH terminal, type $ env | grep EDITOR)?

**Comment by stevepowell99** [comment] 2015-04-23 13:42
EDITOR=/usr/bin/gedit
No errors in the log file. 
Sorry don't understand "what screen are you on".
Desktop environment is mate.
Error message in terminal is:

  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 392, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/local/lib/python2.7/dist-packages/urwid/raw_display.py", line 492, in parse_input
    callback(processed, processed_codes)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 399, in _update
    self.process_input(keys)
  File "/usr/local/lib/python2.7/dist-packages/urwid/main_loop.py", line 499, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/local/lib/python2.7/dist-packages/simplenote_cli/sncli.py", line 631, in gui_frame_keypress
    content = self.exec_cmd_on_note(note)
  File "/usr/local/lib/python2.7/dist-packages/simplenote_cli/sncli.py", line 93, in exec_cmd_on_note
    tf = temp.tempfile_create(note if note else None, raw=raw)
  File "/usr/local/lib/python2.7/dist-packages/simplenote_cli/temp.py", line 21, in tempfile_create
    tf.write(note['content'])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201c' in position 1538: ordinal not in range(128)

**Comment by axs221** [comment] 2015-04-24 14:15
Thanks! It looks like you are using Unicode, and the Python "tempfile" library is being used. tempfile doesn't directly support Unicode, so sncli would need to be modified to encode the unicode string contents you are trying to save for the note. http://stackoverflow.com/questions/10490816/how-to-create-a-temporary-file-with-unicode-encoding

**Comment by axs221** [comment] 2015-04-25 22:47
Hi Steve,

I have committed a change in the master branch that should fix your issue. 

I was able to reproduce your issue. Issue #13 is related. I also found a separate issue with Gedit where changes made in Gedit weren't being recognized by the program, resulting in a "note unchanged" message. This should be fixed as well. 

Please let me know if you have any issues editing or saving still. If not I will close this issue soon.

**Closed** 2015-05-10 00:56 UTC
